export const GAME_CONFIG = {

    WIDTH : 1400,
    HEIGHT : 800,
    PATH_MOVEMENT_RES: 20,
    PATH_COLLISION_RES: 50,

    PATH_PRESET : "path0",
    STARTING_LIVES: 250,
    STARTING_MONEY: 650,
    STARTING_ROUND: 1

};